### PR TITLE
validation

### LINKED ISSUE #27: Auth Validation
Add client side validation to fields for auth 

- login screen
- signup screen
- forgor screen

### PR DESCRIPTION
**Pull request by zzteddy**

### CODE REVIEW

**Comment by StevenEgnaczyk** [comment]
QuestionMark
Is there a reason I can't create an account?

**Review by StevenEgnaczyk — DISMISSED** [review]
Create account doesn't work

**Comment by zzteddy** [comment]
this is due to account already existing, I will add a check and display appropriate message

**Review by willlemon9573 — APPROVED** [review]
good

**Pull request merged**
