### PR TITLE
Changes to Navigation

### PR DESCRIPTION
**Pull request by StevenEgnaczyk**
Changed navigation.

### CODE REVIEW

**Review by zzteddy — APPROVED** [review]
lgtm!

**Comment by StevenEgnaczyk** [comment]
review my code :D

**Comment by StevenEgnaczyk** [comment]
I spent 3 hours on it and found the solution in a 5 minute youtube video by an indian guy using a Simpsons app as an example

**Comment by zzteddy** [comment]
bro i did

**Comment by StevenEgnaczyk** [comment]
did what. I reveiwed ur code dawg

**Comment by StevenEgnaczyk** [comment]
this is new

**Comment by StevenEgnaczyk** [comment]
god I hopwe you all get an individual email for each comment

**Comment by zzteddy** [comment]
> lgtm!

^^^^

**Comment by StevenEgnaczyk** [comment]
i adde  mor

**Pull request closed without merging**
